export const metadata = {
  title: "about",
  description: "Generated by create next app",
};


export default function About() {
  return (
    <div >
      <h1> Página de About     </h1>

         <li> <a href=".."> volver a la página de homne   </a></li>
         <li> <a href="./profile"> esta es otra página  </a></li>
         <li> <a href="./blog"> ir a los blogs </a></li>
         <li> <a href="./products"> ir a los productos </a></li>
         
    </div>
  );
}
