import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body >
      <header style={{backgroundColor: 'lightblue', padding: '1rem', color:'brown'}}> Este es el header </header>
        {children}
        <footer style={{backgroundColor: 'lightblue', padding: '1rem', color:'brown'}}>Este es el footer </footer>
        </body>
      
    </html>
  );
}
